work_dir: ./work_dir/shuffle_combined_model_f_mediapipe
num_epoch: 200
batch_size: 8
device: [0]

model: net.st_gcn.Model

model_args:
  in_channels: 3
  num_class: 2
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'uniform'
  # 아래 두 개는 kwargs로 넘겨져 내부적으로 사용됨

optimizer: SGD
base_lr: 0.1

feeder: feeder.feeder.Feeder

train_feeder_args:
  data_path: /root/fall_detection/dataset/saved_pkl/shuffled_combined_mediapipe_30fps.npy
  label_path: /root/fall_detection/dataset/saved_pkl/shuffled_combined_mediapipe_30fps_labels.pkl
test_feeder_args:
  data_path: /root/fall_detection/dataset/saved_pkl/combined_mediapipe_30fps.npy
  label_path: /root/fall_detection/dataset/saved_pkl/combined_mediapipe_30fps_labels.pkl



