# -*- coding: utf-8 -*-
"""Untitled125.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVUQIUTTe9qz_emmGpsJaXLwfSicyBx0
"""

!pip install moviepy

from moviepy.editor import VideoFileClip, concatenate_videoclips

def make_clip_video(path, save_path, start_t, end_t):
    clip_video = VideoFileClip(path).subclip(start_t, end_t)
    clip_video.write_videofile(save_path)

path1='/content/fall_1.mp4'
path2='/content/fall_2.mp4'
path3='/content/fall_3.mp4'
path4='/content/fall_4.mp4'
path5='/content/fall_5.mp4'
path6='/content/fall_6.mp4'
path7='/content/fall_7.mp4'
path8='/content/fall_8.mp4'
path9='/content/fall_9.mp4'
path10='/content/fall_10.mp4'

make_clip_video(path1, 'normal_data1.mp4', 10, 20)
make_clip_video(path2, 'normal_data2.mp4', 10, 20)
make_clip_video(path3, 'normal_data3.mp4', 10, 20)
make_clip_video(path4, 'normal_data4.mp4', 10, 20)
make_clip_video(path5, 'normal_data5.mp4', 10, 20)
make_clip_video(path6, 'normal_data6.mp4',10, 20)
make_clip_video(path7, 'normal_data7.mp4',10, 20)
make_clip_video(path8, 'normal_data8.mp4', 10, 20)
make_clip_video(path9, 'normal_data9.mp4',10, 20)
make_clip_video(path10, 'normal_data10.mp4',10, 20)
#make_clip_video(path11, 'normal_data11.mp4',10, 20)
#make_clip_video(path12, 'normal_data12.mp4', 10, 20)
#make_clip_video(path13, 'normal_data13.mp4', 10, 20)
#make_clip_video(path14, 'normal_data14.mp4', 10, 20)

make_clip_video(path1, 'falling_data1.mp4', 22, 32)
make_clip_video(path2, 'falling_data2.mp4', 40, 50)
make_clip_video(path3, 'falling_data3.mp4', 40, 50)
make_clip_video(path4, 'falling_data4.mp4', 38, 48)
make_clip_video(path5, 'falling_data5.mp4', 36, 46)
make_clip_video(path6, 'falling_data6.mp4', 36, 46)
make_clip_video(path7, 'falling_data7.mp4', 36, 46)
make_clip_video(path8, 'falling_data8.mp4', 40, 50)
make_clip_video(path9, 'falling_data9.mp4', 40, 50)
make_clip_video(path10, 'falling_data10.mp4', 39, 49)
#make_clip_video(path11, 'normal_data11.mp4', 7, 38)
#make_clip_video(path12, 'normal_data12.mp4', 5, 34)
#make_clip_video(path13, 'normal_data13.mp4', 5, 36)
#make_clip_video(path14, 'normal_data14.mp4', 6, 37)

from moviepy.editor import VideoFileClip, concatenate_videoclips

# 1. 영상 파일 경로 리스트
clip_paths = [
    '/content/fall_1.mp4',
    '/content/fall_2.mp4',
    '/content/fall_3.mp4',
]

clips = [VideoFileClip(path) for path in clip_paths]
combined_n = concatenate_videoclips(clips)
combined_n.write_videofile("falling_original.mp4")

clips = [f]
combined_n = concatenate_videoclips(clips)

mp4='/content/C_3_7_8_BU_SMB_09-02_12-51-37_CB_RGB_DF2_M2.mp4'
make_clip_video(mp4, 'abnormal.mp4', 19, 29)

